#!/bin/sh

#basic init process

mount -t proc none /proc
mount -t sysfs none /sys
cat << !
    HELLO WORLD
                                             
!

chmod +x test
./test
./test

exec /bin/sh +m
