#!/bin/sh

chmod +x test1
chmod +x test2
chmod +x test3

chmod +x background

./background &
./background &
./background &
#./background &
#./background &

time ./test1 0
time ./test2 1
time ./test3 2

counter_a=0
counter_b=0

while [ "$counter_a" -lt 10 ]
do
    counter_b=0
    echo prolaz $counter_a
    while [ "$counter_b" -lt 10 ]
    do
        ./test1 $counter_b &
        ./test2 $counter_b &
        
        if [ $counter_b -eq 9 ]; then
            ./test3 $counter_b
        else
            ./test3 $counter_b &
        fi

        counter_b=$((counter_b+1))
    done

    counter_a=$((counter_a+1))
done

sleep 100000000
