#!/bin/sh

chmod +x test1
chmod +x test2
chmod +x test3

time ./test1 t1 &
time ./test3 t3 &
time ./test3 t3 &
time ./test2 t2

time ./test1 t1 &
time ./test1 t1 &
time ./test2 t2 &

sleep 1

time ./test3 t3 &
time ./test3 t3 &
time ./test3 t3 &

sleep 1

time ./test2 t2 &
time ./test2 t2 &
time ./test1 t1

time ./test2 t2 &
time ./test2 t2 &
time ./test3 t3 &
time ./test1 t1 &
time ./test1 t1 &


sleep 100000000