#!/bin/sh

chmod +x test1
chmod +x test2
chmod +x test3

chmod +x background

./background &
./background &
#./background &
#./background &
#./background &

time ./test3 2

counter_a=0
counter_b=0

while [ "$counter_a" -lt 10 ]
do
    counter_b=0
    echo prolaz $counter_a
    while [ "$counter_b" -lt 10 ]
    do    
        if [ $counter_b -eq 9 ]; then
            time ./test3 $counter_b
        else
            time ./test3 $counter_b &
        fi

        counter_b=$((counter_b+1))
    done

    counter_a=$((counter_a+1))
done

time ./test3 2